### ISSUE TITLE
Generating non-existing types

### ISSUE THREAD

**Issue by johanneshoff** [oapi-codegen/oapi-codegen#1916]
I have a schema that fails to build because it references non-existing types. This is with v2.4.1. This same schema worked in v2.3.0. I've done my best to reduce it to a minimal case.

I build it as follows:
```
oapi-codegen --package openapi --generate types -o types.go schema.json
oapi-codegen --package openapi --generate client -o client.go schema.json
go build ./...
```

And get the result
```
types.go:31:5: undefined: OK200A
```

`schema.json` is as below:
```
{
  "openapi": "3.0.3",
  "paths": {
    "/foo": {
      "get": {
        "responses": {
          "200": {
            "$ref": "#/components/responses/OK_200"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "A": {
        "type": "object",
        "properties": {
          "a": {
            "type": "string",
            "enum": ["value"]
          }
        }
      },
      "B": {
        "type": "object",
        "properties": {
          "b": {
            "type": "string"
          }
        }
      }
   },
    "responses": {
      "OK_200": {
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/A"
                },
                {
                  "$ref": "#/components/schemas/B"
                }
              ]
            }
          }
        }
      }
    }
  }
}
```

**Comment by johanneshoff** [comment]
Possibly related (but not the same as) #1905

**Comment by mromaszewicz** [comment]
The bug was that GenerateTypeDefsForOperation() collected AdditionalTypes from params and request bodies but not from response content schemas (commit 7787164d, labeled as fixing #1306). The missing loop over op.Responses[].Contents[].Schema was added post-v2.4.1. Reproducing the issue with current HEAD confirms the generated types.go defines OK200A correctly (line 71), and the client.go compiles against it. The original undefined-type error no longer occurs.

Closing as fixed. If you can still reproduce on a recent release, please reopen with the exact spec and version used.
