### ISSUE TITLE
undefined security scheme context key type when securitySchemes component is missing

### ISSUE THREAD

**Issue by kitosforos** [oapi-codegen/oapi-codegen#2367]
After upgrading to v2.7.0, generated code fails to compile when the spec uses security at the top level or operation level but does not define the corresponding entry in components/securitySchemes.

**Minimal spec to reproduce:**

```
openapi: "3.0.0"
info:
  title: Test
  version: 1.0.0
security:
  - api_key: []
paths:
  /hello:
    get:
      operationId: getHello
      responses:
        "200":
          description: ok
```

```
oapi-codegen -generate types,gin,strict-server -o gen.go -package api spec.yaml
```

**Generated output:**

```
const (
    Api_keyScopes apiKeyContextKey = "api_key.Scopes"
)
```
```
gen.go:20:16: undefined: apiKeyContextKey
```

The constant references `apiKeyContextKey` but the type definition `type apiKeyContextKey string` is never emitted.

Adding `components/securitySchemes` fixes it -- the type is generated correctly. But the tool should not produce uncompilable code for a spec that was previously accepted, wdyt?

**Comment by mromaszewicz** [comment]
This is an unintended behavior from #1187 

You're creating a security requirement for all API's, but not defining it. I'd argue you have an incomplete spec, but yeah, it's a regression.

The PR I linked assumes the spec is self-referentially correct, and two different parts of the generator assume that the other side exists.

I could detect that a spec is referring to a security scheme that doesn't exist, and silently drop emitting the scopes, but that also creates non-obvious behavior.

**Comment by kitosforos** [comment]
should we add a warning or smth then?

**Comment by mromaszewicz** [comment]
I'm leaning towards dropping the constants. Haven't had a chance to work on it.
